

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-cli
    container_name: laravel-app
    working_dir: /var/www/html
    user: "${UID}:${GID}"
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    networks:
      - app-network
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-blog
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myapp-phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
